name: Release

on:
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  blinux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install cmake pkg-config libfontconfig-dev libgtk-3-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build
        run: cargo build --frozen --profile release-lto --bin lapce

      - name: Gzip
        run: |
          tar -zcvf ./Lapce-linux.tar.gz ./target/release-lto/lapce
      - run: |
          gh release create ${{ github.run_number }} ./Lapce-linux.tar.gz ./target/release-lto/lapce
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell:
          bash

